# options for analysis running
run:
  # available CPUs number
  concurrency: 1

  # (vet, vetshadow): Vet examines Go source code and reports suspicious
  # constructs, such as Printf calls whose arguments do not align with the
  # format string.
  govet:
    # report about shadowed variables
    check-shadowing: true

  # Errcheck is a program for checking for unchecked errors in go programs.
  # These unchecked errors can be critical bugs in some cases.
  errcheck:
    # report about not checking of errors in type assetions: `a := b.(MyStruct)`;
    check-type-assertions: true
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    check-blank: true

  unused:
    # treat code as a program (not a library) and report unused exported identifiers; default is false.
    # XXX: if you enable this setting, unused will report a lot of false-positives in text editors:
    # if it's called for subdir of a project it can't find funcs usages. All text editor integrations
    # with golangci-lint call it on a directory with the changed file.
    check-exported: false

  # Golint differs from gofmt. Gofmt reformats Go source code, whereas golint
  # prints out style mistakes
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.8

  # Finds repeated strings that could be replaced by a constant
  goconst:
    # minimal length of string constant, 3 by default
    min-len: 4
    # minimal occurrences count to trigger, 3 by default
    min-occurrences: 3

  # Goimports does everything that gofmt does. Additionally it checks unused imports.
  # Gofmt checks whether code was gofmt-ed. By default this tool runs with -s
  # option to check for code simplification.
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com

  # Go linter that checks if package imports are in a list of acceptable packages
  depguard:
    list-type: blacklist

  # Reports unused function parameters
  unparam:
    # Inspect exported functions, default is false. Set to true if no external program/library imports your code.
    # XXX: if you enable this setting, unparam will report a lot of false-positives in text editors:
    # if it's called for subdir of a project it can't find external interfaces. All text editor integrations
    # with golangci-lint call it on a directory with the changed file.
    check-exported: false

  # Finds naked returns in functions greater than a specified function length
  nakedret:
    # make an issue if func has more lines of code than this setting and it has naked returns; default is 30
    max-func-lines: 0

  # Finds slice declarations that could potentially be preallocated
  prealloc:
    # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them.
    # True by default.
    simple: true
    range-loops: true # Report preallocation suggestions on range loops, true by default
    for-loops: false # Report preallocation suggestions on for loops, false by default

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number
  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

linters:
  enable:
    # https://golang.org/cmd/vet/
    - govet
    # https://github.com/kisielk/errcheck
    - errcheck
    # https://staticcheck.io/
    - staticcheck
    # https://github.com/dominikh/go-tools/tree/master/cmd/unused
    - unused
    # https://github.com/dominikh/go-tools/tree/master/cmd/gosimple
    - gosimple
    # https://github.com/opennota/check
    - varcheck
    # https://github.com/gordonklaus/ineffassign
    - ineffassign
    # https://github.com/remyoudompheng/go-misc/tree/master/deadcode
    - deadcode
    # https://github.com/golang/lint
    - golint
    # https://github.com/securego/gosec
    - gosec
    # https://github.com/mdempsky/unconvert
    - unconvert
    # https://godoc.org/golang.org/x/tools/cmd/goimports
    - goimports
    # https://github.com/OpenPeeDeeP/depguard
    - depguard
    # https://github.com/client9/misspell
    - misspell
    # https://github.com/mvdan/unparam
    - unparam
    # https://github.com/alexkohler/nakedret
    - nakedret
    # https://github.com/alexkohler/prealloc
    - prealloc
    # https://github.com/leighmcculloch/gochecknoinits
    - gochecknoinits
  enable-all: false
